[package]
name = "rust-game"
version = "0.1.0"
authors = ["Derek Crosson <derek@designcafe.co.za>"]
edition = "2018"

[[bin]]
name = "rust-game"

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"
